from .Apple import AppleAPI
from .Api import ApiPlatform
from .Carbon import CarbonAPI
from .Deezer import DeezerAPI
from .DirectMedia import DirectMediaAPI
from .Gaana import GaanaAPI
from .JioSaavn import JioSaavnAPI
from .Kick import KickAPI
from .MXPlayer import MXPlayerAPI
from .Resso import RessoAPI
from .Soundcloud import SoundAPI
from .Spotify import SpotifyAPI
from .Suggestions import send_related_tracks
from .Telegram import TeleAPI
from .Tidal import TidalAPI
from .Twitch import TwitchAPI
from .Youtube import YouTubeAPI
